//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstDemoLazyLoading
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor : Person
    {
        public Instructor()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public string Location { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
    }
}
