//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Klant = new HashSet<Klant>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public decimal Prijs { get; set; }
    
        public virtual ICollection<Klant> Klant { get; set; }
    }
}
