//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/21/2013 3:09:01 PM
namespace WcfDataServicesDemo.CLient.MijnODataService
{
    
    /// <summary>
    /// There are no comments for MijnContext in the schema.
    /// </summary>
    public partial class MijnContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new MijnContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MijnContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("WcfDataServicesDemo", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("WcfDataServicesDemo.CLient.MijnODataService", typeName.Substring(19)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WcfDataServicesDemo.CLient.MijnODataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("WcfDataServicesDemo.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Personen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Persoon> Personen
        {
            get
            {
                if ((this._Personen == null))
                {
                    this._Personen = base.CreateQuery<Persoon>("Personen");
                }
                return this._Personen;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Persoon> _Personen;
        /// <summary>
        /// There are no comments for Producten in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Product> Producten
        {
            get
            {
                if ((this._Producten == null))
                {
                    this._Producten = base.CreateQuery<Product>("Producten");
                }
                return this._Producten;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Product> _Producten;
        /// <summary>
        /// There are no comments for Personen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPersonen(Persoon persoon)
        {
            base.AddObject("Personen", persoon);
        }
        /// <summary>
        /// There are no comments for Producten in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProducten(Product product)
        {
            base.AddObject("Producten", product);
        }
    }
    /// <summary>
    /// There are no comments for WcfDataServicesDemo.Persoon in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Personen")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Persoon : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Persoon object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="geboortedatum">Initial value of Geboortedatum.</param>
        /// <param name="email">Initial value of Email.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Persoon CreatePersoon(int ID, global::System.DateTime geboortedatum, string email)
        {
            Persoon persoon = new Persoon();
            persoon.Id = ID;
            persoon.Geboortedatum = geboortedatum;
            persoon.Email = email;
            return persoon;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Naam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Naam
        {
            get
            {
                return this._Naam;
            }
            set
            {
                this.OnNaamChanging(value);
                this._Naam = value;
                this.OnNaamChanged();
                this.OnPropertyChanged("Naam");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Naam;
        partial void OnNaamChanging(string value);
        partial void OnNaamChanged();
        /// <summary>
        /// There are no comments for Property Geboortedatum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Geboortedatum
        {
            get
            {
                return this._Geboortedatum;
            }
            set
            {
                this.OnGeboortedatumChanging(value);
                this._Geboortedatum = value;
                this.OnGeboortedatumChanged();
                this.OnPropertyChanged("Geboortedatum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Geboortedatum;
        partial void OnGeboortedatumChanging(global::System.DateTime value);
        partial void OnGeboortedatumChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Producten in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Product> Producten
        {
            get
            {
                return this._Producten;
            }
            set
            {
                this._Producten = value;
                this.OnPropertyChanged("Producten");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Product> _Producten = new global::System.Data.Services.Client.DataServiceCollection<Product>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfDataServicesDemo.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Producten")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Product : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="prijs">Initial value of Prijs.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Product CreateProduct(int ID, decimal prijs)
        {
            Product product = new Product();
            product.Id = ID;
            product.Prijs = prijs;
            return product;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Omschrijving2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Omschrijving2
        {
            get
            {
                return this._Omschrijving2;
            }
            set
            {
                this.OnOmschrijving2Changing(value);
                this._Omschrijving2 = value;
                this.OnOmschrijving2Changed();
                this.OnPropertyChanged("Omschrijving2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Omschrijving2;
        partial void OnOmschrijving2Changing(string value);
        partial void OnOmschrijving2Changed();
        /// <summary>
        /// There are no comments for Property Prijs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Prijs
        {
            get
            {
                return this._Prijs;
            }
            set
            {
                this.OnPrijsChanging(value);
                this._Prijs = value;
                this.OnPrijsChanged();
                this.OnPropertyChanged("Prijs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Prijs;
        partial void OnPrijsChanging(decimal value);
        partial void OnPrijsChanged();
        /// <summary>
        /// There are no comments for Klanten in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Persoon> Klanten
        {
            get
            {
                return this._Klanten;
            }
            set
            {
                this._Klanten = value;
                this.OnPropertyChanged("Klanten");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Persoon> _Klanten = new global::System.Data.Services.Client.DataServiceCollection<Persoon>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
